
export const EnglishData4 = [
    {
        Thumbnail: 'https://i.ytimg.com/vi/e0PSWpuyY8/default.jpg',
        videoTittle: "Enough | 90-dars",
        ID: 1,
        videoLink: 'https://www.youtube.com/embed/e0PSWpuyY8',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/Z0Zqo-LfmSg/default.jpg',
        videoTittle: "Too | 91-dars",
        ID: 2,
        videoLink: 'https://www.youtube.com/embed/Z0Zqo-LfmSg',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/hSlJmfz4hUw/default.jpg',
        videoTittle: "Word order 1 | 92-dars",
        ID: 3,
        videoLink: 'https://www.youtube.com/embed/hSlJmfz4hUw',
    },
    {
        videoTittle: "Word order 2 | 93-dars",
        Thumbnail: 'https://i.ytimg.com/vi/QaNWQkzDZyo/default.jpg',
        ID: 4,
        videoLink: 'https://www.youtube.com/embed/QaNWQkzDZyo',
    },
    {
        videoTittle: "Still vs Yet | 94-dars",
        Thumbnail: 'https://i.ytimg.com/vi/7aG3-5hKaDY/default.jpg',
        ID: 5,
        videoLink: 'https://www.youtube.com/embed/7aG3-5hKaDY',
    },
    {
        videoTittle: "Give me.. / Give it to... | 95-dars",
        Thumbnail: 'https://i.ytimg.com/vi/yJ4YCzrfSVE/default.jpg',
        ID: 6,
        videoLink: 'https://www.youtube.com/embed/yJ4YCzrfSVE',
    },
    {
        videoTittle: "At / On / In | 96-dars",
        Thumbnail: 'https://i.ytimg.com/vi/UR-5WGOz6BQ/default.jpg',
        ID: 7,
        videoLink: 'https://www.youtube.com/embed/UR-5WGOz6BQ',
    },
    {
        videoTittle: "From... to, Until, Since, For | 97-dars",
        Thumbnail: 'https://i.ytimg.com/vi/lwpu0ZAVQBg/default.jpg',
        ID: 8,
        videoLink: 'https://www.youtube.com/embed/lwpu0ZAVQBg',
    },
    {
        videoTittle: "Deleted video                                                                                        ",
        Thumbnail: 'https://i.ytimg.com/vi/DPof4n7-yjo/default.jpg',
        ID: 9,
        videoLink: 'https://www.youtube.com/embed/DPof4n7-yjo',
    },
    {
        videoTittle: "Before, After, During, While | 98-dars",
        Thumbnail: 'https://i.ytimg.com/vi/-kRhiZzOuiA/default.jpg',
        ID: 10,
        videoLink: 'https://www.youtube.com/embed/-kRhiZzOuiA',
    },
    {
        videoTittle: "In / At (Places) | 99-dars",
        Thumbnail: 'https://i.ytimg.com/vi/v6PALjmaoAs/default.jpg',
        ID: 11,
        videoLink: 'https://www.youtube.com/embed/v6PALjmaoAs',
    },
    {
        videoTittle: "To / In / At (Places) | 100-dars",
        Thumbnail: 'https://i.ytimg.com/vi/8_FHp_5RCE4/default.jpg',
        ID: 12,
        videoLink: 'https://www.youtube.com/embed/8_FHp_5RCE4',
    },
    {
        videoTittle: "Lesson Number 101                                                                                        ",
        Thumbnail: 'https://i.ytimg.com/vi/aZ1WmtRpaIE/default.jpg',
        ID: 13,
        videoLink: 'https://www.youtube.com/embed/aZ1WmtRpaIE',
    },
    {
        videoTittle: "On / Under / Behind (prepositions) | 101-dars",
        Thumbnail: 'https://i.ytimg.com/vi/Usq-rFq3dIc/default.jpg',
        ID: 14,
        videoLink: 'https://www.youtube.com/embed/Usq-rFq3dIc',
    },
    {
        videoTittle: "Up / Over / Through (prepositions) | 102-dars",
        Thumbnail: 'https://i.ytimg.com/vi/cBricTWWU/default.jpg',
        ID: 15,
        videoLink: 'https://www.youtube.com/embed/cBricTWWU',
    },
    {
        videoTittle: "At / by / With / Without/ About (prepositions) | 103-dars",
        Thumbnail: 'https://i.ytimg.com/vi/XEvJ15yfmNQ/default.jpg',
        ID: 16,
        videoLink: 'https://www.youtube.com/embed/XEvJ15yfmNQ',
    },
    {
        videoTittle: "Afraid of... / On holiday (word + prpositions) | 104-dars",
        Thumbnail: 'https://i.ytimg.com/vi/sgYZN4diuQ/default.jpg',
        ID: 17,
        videoLink: 'https://www.youtube.com/embed/sgYZN4diuQ',
    },
    {
        videoTittle: "Look at / Listen to (verb + prepostions) | 105-dars",
        Thumbnail: 'https://i.ytimg.com/vi/5_G4o7TDk-c/default.jpg',
        ID: 18,
        videoLink: 'https://www.youtube.com/embed/5_G4o7TDk-c',
    },
    {
        videoTittle: "Lesson Number 106                                                                                        ",
        Thumbnail: 'https://i.ytimg.com/vi/r-y38OYSS-U/default.jpg',
        ID: 19,
        videoLink: 'https://www.youtube.com/embed/r-y38OYSS-U',
    },
    {
        videoTittle: "Lesson Number 107                                                                                      ",
        Thumbnail: 'https://i.ytimg.com/vi/yXGGPULdSTs/default.jpg',
        ID: 20,
        videoLink: 'https://www.youtube.com/embed/yXGGPULdSTs',
    },
    {
        videoTittle: "Go in / Fall off / Run away (phrasal verb 1) | 106-dars",
        Thumbnail: 'https://i.ytimg.com/vi/aNkPNabL2tc/default.jpg',
        ID: 21,
        videoLink: 'https://www.youtube.com/embed/aNkPNabL2tc',
    },
    {
        videoTittle: "Put on your shoes / Put your shoes on  (phrasal verb 1) | 107-dars", 
        Thumbnail: 'https://i.ytimg.com/vi/Y2gOg5fQDO0/default.jpg',
        ID: 22,
        videoLink: 'https://www.youtube.com/embed/Y2gOg5fQDO0',

    },
]