export const EnglishData3 = [
    {
        Thumbnail: 'https://i.ytimg.com/vi/khlpr-PjsCo/default.jpg',
       videoTittle:" Pronouns Part 1 | 61-dars | Ingliz tilini 0 dan o'rganish                              ",
        ID: 1,    
        videoLink: 'https://www.youtube.com/embed/khlpr-PjsCo',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/w4e2YVU5vbk/default.jpg',
       videoTittle:" Pronouns Part 2 | 62-dars | Ingliz tilini 0 dan o'rganish                              ",
        ID: 2,    
        videoLink: 'https://www.youtube.com/embed/w4e2YVU5vbk',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/FmFilejfH00/default.jpg',
       videoTittle:" -ning kelishik qo'shimchasi | 63-dars | Ingliz tilini 0 dan o'rganish                  ",
        ID: 3,    
        videoLink: 'https://www.youtube.com/embed/FmFilejfH00',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/9cO0taZ6zLA/default.jpg',
       videoTittle:" A and an articles | 64-dars | Ingliz tilini 0 dan o'rganish                            ",
        ID: 4,    
        videoLink: 'https://www.youtube.com/embed/9cO0taZ6zLA',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/q5rWCTq47iU/default.jpg',
       videoTittle:" Countable and Uncountable nouns | 66-dars | Ingliz tilini 0 dan o'rganish              ",
        ID: 5,    
        videoLink: 'https://www.youtube.com/embed/q5rWCTq47iU',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/EVdjIIbRkrI/default.jpg',
       videoTittle:" Countable and Uncountable nouns | 67-dars | Ingliz tilini 0 dan o'rganish              ",
        ID: 6,    
        videoLink: 'https://www.youtube.com/embed/EVdjIIbRkrI',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/8cEmTtO6mDE/default.jpg',
       videoTittle:" Singular and Plural nouns | 65-dars | Ingliz tilini 0 dan o'rganish                    ",
        ID: 7,    
        videoLink: 'https://www.youtube.com/embed/8cEmTtO6mDE',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/49RNu3zbR5U/default.jpg',
       videoTittle:" A vs The | Articles | 68-dars | Ingliz tilini 0 dan o'rganish                          ",
        ID: 8,    
        videoLink: 'https://www.youtube.com/embed/49RNu3zbR5U',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/dOp6p--WgS4/default.jpg',
       videoTittle:" The article | 69-dars | Ingliz tilini 0 dan o'rganish                                  ",
        ID: 9,    
        videoLink: 'https://www.youtube.com/embed/dOp6p--WgS4',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/rKJQv8Vquuc/default.jpg',
       videoTittle:" When NOT to use 'the' | 71-dars | Ingliz tilini 0 dan o'rganish    ",
        ID: 10    ,
        videoLink: 'https://www.youtube.com/embed/rKJQv8Vquuc',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/io7vw34DGio/default.jpg',
       videoTittle:" Go to work vs Go home | 70-dars | Ingliz tilini 0 dan o'rganish                        ",
        ID: 11    ,
        videoLink: 'https://www.youtube.com/embed/io7vw34DGio',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/UY6oRh4cC_4/default.jpg',
       videoTittle:" That/This/Those/These | 73-dars | Ingliz tilini 0 dan o'rganish                        ",
        ID: 12    ,
        videoLink: 'https://www.youtube.com/embed/UY6oRh4cC_4',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/S_YCCGK-Zxc/default.jpg',
       videoTittle:" Names of places | 72-dars | Ingliz tilini 0 dan o'rganish                              ",
        ID: 13,
        videoLink: 'https://www.youtube.com/embed/S_YCCGK-Zxc',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/ddC4HqzPevA/default.jpg',
       videoTittle:" One vs Ones | 74-dars | Ingliz tilini 0 dan o'rganish                                  ",
        ID: 14    ,
        videoLink: 'https://www.youtube.com/embed/ddC4HqzPevA',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/RCC6J4wlw9Q/default.jpg',
       videoTittle:" Some vs Any | 75-dars | Ingliz tilini 0 dan o'rganish                                  ",
        ID: 15    ,
        videoLink: 'https://www.youtube.com/embed/RCC6J4wlw9Q',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/eA1grZkCozU/default.jpg',
       videoTittle:" No + any / No / None | 76-dars | Ingliz tilini 0 dan o'rganish                         ",
        ID: 16    ,
        videoLink: 'https://www.youtube.com/embed/eA1grZkCozU',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/Jza-8IOZsM8/default.jpg',
       videoTittle:" Not+anybody vs Nobody | 77-dars | Ingliz tilini 0 dan o'rganish                        ",
        ID: 17    ,
        videoLink: 'https://www.youtube.com/embed/Jza-8IOZsM8',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/Q8huffFVv70/default.jpg',
       videoTittle:" Somebody/Anything/Nowhere  | 78-dars | Ingliz tilini 0 dan o'rganish                   ",
        ID: 18    ,
        videoLink: 'https://www.youtube.com/embed/Q8huffFVv70',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/waJTRVrGtNM/default.jpg',
       videoTittle:" Every vs All | 79-dars | Ingliz tilini 0 dan o'rganish                                 ",
        ID: 19    ,
        videoLink: 'https://www.youtube.com/embed/waJTRVrGtNM',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/NAaBhYgOvzQ/default.jpg',
       videoTittle:" All/Most/Some/Any | 80-dars | Ingliz tilini 0 dan o'rganish                            ",
        ID: 20    ,
        videoLink: 'https://www.youtube.com/embed/NAaBhYgOvzQ',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/0uU9VH2p67Y/default.jpg',
       videoTittle:" Both / Either / Neither | 81-dars | Ingliz tilini 0 dan o'rganish                      ",
        ID: 21    ,
        videoLink: 'https://www.youtube.com/embed/0uU9VH2p67Y',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/iFTrQy_3-O8/default.jpg',
       videoTittle:" A little vs A few | 83-dars | Ingliz tilini 0 dan o'rganish                            ",
        ID: 22    ,
        videoLink: 'https://www.youtube.com/embed/iFTrQy_3-O8',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/TloXXwIeSMo/default.jpg',
       videoTittle:" A lot / Much / Many | 82-dars | Ingliz tilini 0 dan o'rganish                          ",
        ID: 23    ,
        videoLink: 'https://www.youtube.com/embed/TloXXwIeSMo',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/OaPMtoGixBs/default.jpg',
       videoTittle:" Adjectives | 84-dars | Ingliz tilini 0 dan o'rganish                                   ",
        ID: 24    ,
        videoLink: 'https://www.youtube.com/embed/OaPMtoGixBs',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/rDdj4I2FSZg/default.jpg',
       videoTittle:" Adverbs | 85-dars | Ingliz tilini 0 dan o'rganish                                      ",
        ID: 25    ,
        videoLink: 'https://www.youtube.com/embed/rDdj4I2FSZg',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/pcjGsmbDc3o/default.jpg',
       videoTittle:" Old vs Older | 86-dars | Ingliz tilini 0 dan o'rganish                                 ",
        ID: 26    ,
        videoLink: 'https://www.youtube.com/embed/pcjGsmbDc3o',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/p091YqwUMWY/default.jpg',
       videoTittle:" Older / More expensive than... | 87-dars | Ingliz tilini 0 dan o'rganish               ",
        ID: 27    ,
        videoLink: 'https://www.youtube.com/embed/p091YqwUMWY',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/aHd3KbWPzoM/default.jpg',
       videoTittle:" Not as... as | 88-dars | Ingliz tilini 0 dan o'rganish                                 ",
        ID: 28    ,
        videoLink: 'https://www.youtube.com/embed/aHd3KbWPzoM',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/XRqG17D0zVw/default.jpg',
       videoTittle:" The oldest / The most expensive | 89-dars | Ingliz tilini 0 dan o'rganish Private video",
        ID: 29    ,
        videoLink: 'https://www.youtube.com/embed/XRqG17D0zVw',
    },
    {
        Thumbnail: 'https://i.ytimg.com/vi/d-fvgkbTED0/default.jpg',
       videoTittle:" Alphabet | Kirish | Ingliz tilini 0 dan o'rganish                                      ",
        ID: 30    ,
        videoLink: 'https://www.youtube.com/embed/d-fvgkbTED0',
    },
]