import Courses from '@/companents/Courses'

import Header from '@/companents/Header'
import Services from '@/companents/Services'
import styles from "../styles/Home.module.css"
import Head from 'next/head'
import { createContext, useState } from "react";  

import ReactSwitch from "react-switch";


export const ThemeContext = createContext(null);
export default function Home() {

  const [theme, setTheme] = useState("light");

  const toggleTheme = () => {
    setTheme((curr) => (curr === "dark" ? "light" : "dark"));
  };
  return (

    <>
  

      <Head>
        <title>SardorDevs Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_03.ico" />
      </Head>


      <>
 

        <ThemeContext.Provider value={{ theme, toggleTheme }}>

          <section id={theme} className={styles.Web_App}>

            <Header />

            <div className="switch">


              <label className='modeicon' htmlFor="small-radius-switch">

                <ReactSwitch
                  id={"mode"}
                  onChange={toggleTheme} checked={theme === "light"}
                  handleDiameter={28}
                  offColor="#08f"
                  onColor="#0ff"
                  offHandleColor="#0ff"
                  onHandleColor="#08f"
                  height={40}

                  width={70}
                  borderRadius={5}
                  activeBoxShadow="0px 0px 1px 2px #fffc35"
                  uncheckedIcon={
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        height: "100%",
                        fontSize: 15,
                        color: "white",
                        paddingRight: 2
                      }}
                    >
                      off
                    </div>
                  }
                  checkedIcon={
                    <>

                      <div
                        style={{
                          display: "flex",
                          justifyContent: "center",
                          alignItems: "center",
                          height: "100%",
                          fontSize: 15,
                          color: "black",
                          paddingRight: 2
                        }}
                      >
                        On
                      </div> </>
                  }
                  uncheckedHandleIcon={
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        height: "100%",
                        fontSize: 20
                      }}
                    >
                      ⚫
                    </div>
                  }
                  checkedHandleIcon={
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        height: "100%",
                        color: "red",
                        fontSize: 18
                      }}
                    >
                      🔆
                    </div>
                  }
                  className="react-switch"

                />
              </label>
            </div>

            <Services/>
            <Courses />

          </section>
        </ThemeContext.Provider>
      </>


    </>
  )
}
